require "pry"
require "invoker"

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.mock_framework = :mocha

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

ENV["INVOKER_TESTS"] = "true"

def invoker_config
  if Invoker.const_defined?(:CONFIG)
    Invoker::CONFIG
  else
    Invoker.const_set(:CONFIG, mock())
    Invoker::CONFIG
  end
end

def invoker_commander
  if Invoker.const_defined?(:COMMANDER)
    Invoker::COMMANDER
  else
    Invoker.const_set(:COMMANDER, mock())
    Invoker::COMMANDER
  end
end
